---
# tasks file for nsxt_config_edgecluster
#Create
- name: Create Edgecluster Payload
  template:
    src: template_edgecluster.j2
    dest: /tmp/nsxt_edgecluster.yml
  delegate_to: '{{ nsxt.api_host }}'
  when: item.display_name not in (nsxt_edgeclusters.json | json_query('results[*].display_name'))

- name: Create Edgecluster  "{{ item.display_name }}"
  uri:
    url: https://{{ inventory_hostname }}/api/v1/edge-clusters
    method: POST
    status_code: 201
    validate_certs: no
    user: "{{ nsxt.admin_username }}"
    password: "{{ nsxt.admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: "{{ (lookup('template', '/tmp/nsxt_edgecluster.yml')) | from_yaml }}"
  delegate_to: '{{ nsxt.api_host }}'
  when: item.display_name not in (nsxt_edgeclusters.json | json_query('results[*].display_name'))

- name: Remove Edgecluster Profile Payload
  file:
    path: /tmp/nsxt_edgecluster.yml
    state: absent
  delegate_to: '{{ nsxt.api_host }}'
  when: item.display_name not in (nsxt_edgeclusters.json | json_query('results[*].display_name'))


#Update
- name: Create Edgecluster Payload
  template:
    src: template_edgecluster.j2
    dest: /tmp/nsxt_edgecluster.yml
  delegate_to: '{{ nsxt.api_host }}'
  when: item.display_name in (nsxt_edgeclusters.json | json_query('results[*].display_name'))

- name: Update Edgecluster  "{{ item.display_name }}"
  uri:
    url: https://{{ inventory_hostname }}/api/v1/edge-clusters/{{ (nsxt_edgeclusters | json_query('json.results[?display_name==`' + item.display_name + '`].id')).0 }}
    method: PUT
    status_code: 200
    validate_certs: no
    user: "{{ nsxt.admin_username }}"
    password: "{{ nsxt.admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: "{{ (lookup('template', '/tmp/nsxt_edgecluster.yml')) | from_yaml }}"
  delegate_to: '{{ nsxt.api_host }}'
  when: item.display_name in (nsxt_edgeclusters.json | json_query('results[*].display_name'))

- name: Remove Edgecluster Profile Payload
  file:
    path: /tmp/nsxt_edgecluster.yml
    state: absent
  delegate_to: '{{ nsxt.api_host }}'
  when: item.display_name in (nsxt_edgeclusters.json | json_query('results[*].display_name'))
