---
# tasks file for nsxt_config_profile-edgecluster
- name: Get EdgeCluster-Profile "{{ item.display_name }}"
  uri:
    url: https://{{ inventory_hostname }}/policy/api/v1/cluster-profiles
    method: GET
    status_code: 200, 404
    validate_certs: no
    user: "{{ nsxt.admin_username }}"
    password: "{{ nsxt.admin_password }}"
    force_basic_auth: yes
  register: edgecluster_profile
  delegate_to: '{{ nsxt.api_host }}'

- name: Add default parameters
  set_fact:
    payload: "{{ item | combine({ 'resource_type': 'EdgeHighAvailabilityProfile'}) }}"

- name: Exist, Update - add _revision parameter
  set_fact:
    method: 'PUT'
    id: "{{ item.id }}"
    status_code: 200
    payload: "{{ payload | combine({ '_revision': (edgecluster_profile.json | json_query('results[?id==`' + item.id + '`]._revision'))[0] }) }}"
  when: item.id in (edgecluster_profile.json | json_query('results[*].id'))

- name: Create or update EdgeCluster-Profile "{{ item.display_name }}"
  uri:
    url: https://{{ inventory_hostname }}/policy/api/v1/cluster-profiles/{{ id | default('') }}
    method: "{{ method | default('POST') }}"
    status_code: "{{ status_code | default('201') }}"
    validate_certs: no
    user: "{{ nsxt.admin_username }}"
    password: "{{ nsxt.admin_password }}"
    force_basic_auth: yes
    body_format: json
    body:
      "{{ payload }}"
  delegate_to: '{{ nsxt.api_host }}'